feat: business logic
Katibat/java-filmorate pull request #3
Opened 2022-05-23 17:48 UTC by Katibat

2022-05-24 22:30 UTC, kukolev requested changes

2022-05-24 22:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(u->userStorage.getById(u).get())
Нарушение требований кодстайла: Не хватает пробела до и после «->». Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-05-24 22:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public static final LocalDate BIRTHDAY_CINEMA = LocalDate.of(1895, 12, 28);
Эта константа встречается только в этом классе, поэтому ее нужно сделать приватной.

2022-05-25 06:20 UTC, Katibat commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public static final LocalDate BIRTHDAY_CINEMA = LocalDate.of(1895, 12, 28);
точно, спасибо! Исправлено.

2022-05-25 16:35 UTC, kukolev approved these changes

2022-06-07 16:56 UTC, merged